displayName=ItemSource
author=legandaryme026
description=Find ways to obtain Old School RuneScape items
tags=items,wiki,ironman,shops,drops,crafting,spawns,rewards
version=
plugins=com.itemsource.ItemSourcePlugin
build=standard
